G.A. event tracking updates
CriminalInjuriesCompensationAuthority/cica-web pull request #162
Opened 2020-09-09 08:30 UTC by armoj

Adds event tracking for:
* track character count on input/textarea elements
* track each error message individually
* track paste event on input/textarea elements

2020-10-07 14:43 UTC, sinclairs requested changes

2020-10-07 14:43 UTC, sinclairs commented on test/test-fixtures/transformations/resolved html/p-applicant-british-citizen-or-eu-national.js
> +                    <a href="#" role="button" draggable="false" class="govuk-button govuk-modal__continue ga-event--click" tracking-category="modal-button" data-module="govuk-button">Continue applica
Check if data-* should be used... GDS design system might provide a mechanism for data-* and allow buttons to be used if it's easier

2020-10-07 14:43 UTC, sinclairs commented on src/modules/ga/index.js
> +    function elementPasteHandler(element) {
Need some tests for the new functionality: paste, char count, journey duration

2020-10-07 14:43 UTC, sinclairs commented on questionnaire/form-helper.js
> +    const isSubmissionPage = getSectionContext(sectionId) === 'submission';
@BarryPiccinni any strong opinion on not doing this?

2020-10-12 13:59 UTC, BarryPiccinni approved these changes

2020-10-13 14:50 UTC, merged