Bp govuk sign in2
CriminalInjuriesCompensationAuthority/cica-web pull request #281
Opened 2022-11-14 12:45 UTC by BarryPiccinni

2022-11-14 16:11 UTC, armoj requested changes

2022-11-14 16:11 UTC, armoj commented on account/routes.js
> +const signInService = require('../govuk/sign-in/index')();
move the "creation" of the service in to the route itself

2022-11-15 11:17 UTC, BarryPiccinni commented on account/routes.js
> +        res.status(err.statusCode || 404).render('404.njk');
I'm going to leave this at the moment. We don't have a suitable 503 page to cover this, I will ask Graeme to prepare some content for an error page which reflect this scenario.

2022-11-15 11:39 UTC, BarryPiccinni commented on govuk/sign-in/authorisation/index.js
> +            vtr: '[Cl.Cm]'
Yes. This does.

2022-11-15 11:40 UTC, BarryPiccinni commented on govuk/sign-in/authorisation/index.js
> +            scope: ['openid'],
Yep, the array is unnecessary.

2022-11-15 12:10 UTC, BarryPiccinni commented on govuk/sign-in/authorisation/index.js
> +            state: 'STATE',
I have implemented a set of default values with the option to overwrite these by passing them in. Thoughts welcome!

2022-11-15 14:36 UTC, armoj approved these changes

2022-11-15 15:25 UTC, merged