Verify JWT
CriminalInjuriesCompensationAuthority/cica-web pull request #290
Opened 2022-11-24 10:53 UTC by armoj

2022-11-24 10:55 UTC, armoj commented on .gitignore
> +private_key.pem
needs removed

2022-11-24 11:55 UTC, BarryPiccinni requested changes
Could also consider the folder structure - JWT could be used elsewhere in the module, not necessarily just by govuk.

2022-11-24 11:55 UTC, BarryPiccinni commented on account/routes.js
> +        const userIdToken = await signInService.getIdToken(authorisationCode);
I think you were right to rename this function in your original PR, on reflection the routes shouldn't care about Tokens, and it's actually returning the ID anyway, not the token.

2022-11-24 11:55 UTC, BarryPiccinni commented on govuk/sign-in/jwt/index.js
> +    // https://traveling-coderman.net/code/node-architecture/authentication/
Delete please!

2022-11-24 11:55 UTC, BarryPiccinni commented on govuk/sign-in/jwt/index.js
> +            jwt.verify(token, await getKey);
This isn't a full verification. You need to verify the Audience, issuer and algorithms used as a minimum.

2022-11-24 11:55 UTC, BarryPiccinni commented on govuk/sign-in/token/index.js
> +            url: `${process.env.CW_GOVUK_ISSUER_URL}/token`,
You need to grab this from the mighty issuer!! Can't assume this will always be the endpoint

2022-11-24 11:55 UTC, BarryPiccinni commented on govuk/sign-in/token/index.js
> +                    aud: `${process.env.CW_GOVUK_ISSUER_URL}/token`,
As above.

2022-11-24 11:55 UTC, BarryPiccinni commented on govuk/sign-in/token/index.js
> +        }
This should all be done by the JWT module. Some of it is out of your control, if the `exp` has expired for example, the `jsonwebtoken` verify function will fail regardless of any of these checks.

2022-11-25 16:01 UTC, BarryPiccinni requested changes

2022-11-25 16:16 UTC, BarryPiccinni approved these changes

2022-11-25 16:22 UTC, merged