Postcode lookup mapping
CriminalInjuriesCompensationAuthority/cica-web pull request #298
Opened 2022-11-30 14:50 UTC by neil-stephen-mcgonigle

-Add address selection to address fields

2022-12-01 18:29 UTC, sinclairs requested changes
This is as far as I got, and the chat we had before we both left for the day. Catch up on Monday 👍

2022-12-01 18:29 UTC, sinclairs commented on src/modules/postcode-lookup/index.js
> +        createSearchResultsElements,
If these aren't part of the public api they could be removed and left private

2022-12-02 12:39 UTC, neil-stephen-mcgonigle commented on app.js
> +app.use(['/apply', '/download', '/address-finder'], async (req, res, next) => {
Removed, it would only be required for instances where /address-finder was called as the initial request prior to session creation.

2022-12-05 09:39 UTC, neil-stephen-mcgonigle commented on address-finder/test/address-finder-service.test.js
> +        });
Pattern implemented!

2023-01-24 09:17 UTC, closed without merging