Postcode lookup technical error
CriminalInjuriesCompensationAuthority/cica-web pull request #311
Opened 2022-12-12 18:25 UTC by neil-stephen-mcgonigle

- add contextualisation for error messages
- add external api call error handling
- refactor new line regex for tests out to a constant

2022-12-15 16:14 UTC, sinclairs requested changes
Saving so far...

2023-01-18 09:52 UTC, neil-stephen-mcgonigle commented on address-finder/test/routes.test.js
> +            );
Leaving as is, discussed with @sinclairs

2023-01-25 10:19 UTC, stephenjmcneill1971 approved these changes

2023-02-03 11:41 UTC, neil-stephen-mcgonigle commented
Backwards incompatible changes with inflight applciations
Proposed version bump to 6.0.0

2023-02-06 18:36 UTC, merged