Add GOV.UK One Login header for authenticated users
CriminalInjuriesCompensationAuthority/cica-web pull request #461
Opened 2024-04-08 11:37 UTC by armoj

2024-04-08 15:28 UTC, BarryPiccinni requested changes
Is it worth revisiting our folder structure here? We've already got:
`./components/govuk/phase-banner`
and now this is adding:
`./components/govuk-one-login/service-header`
Would it make sense to have something more like:
```
./components/govuk/phase banner
./components/govuk/one-login-service-header
```

2024-04-08 15:28 UTC, BarryPiccinni commented on page/page.njk
> +                href: "/account/dashboard",
I'm not entirely clear why this href is hard-coded but `currentUrlPathname` is passed in to the template? Could both just be hard-coded here? Or both set to the value of `currentUrlPathname` if you're concerned that we change the URL in the future?

2024-04-08 15:58 UTC, armoj commented on src/sass/all-ie8.scss
> +@import "../../components/govuk/phase-banner/phase-banner";
nope! good catch. Forgot to remove after helping out with the frontend upgrade!

2024-04-09 15:14 UTC, BarryPiccinni approved these changes

2024-04-10 13:37 UTC, merged